[package]
name = "flower_kernel"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>", "Gegy1000 <gegy1000@gmail.com"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]

